#!/bin/bash
# Download all datasets required for PCA-Triage experiments.
# Usage: bash data/download.sh
#
# Some datasets require manual download due to licensing:
#   - SWaT: Synthetic stand-in generated by code (no download needed)
#   - NASA: Synthetic, generated by code (no download needed)

set -e
RAW_DIR="data/raw"
mkdir -p "$RAW_DIR"

echo "=== PCA-Triage Dataset Download ==="

# 1. TEP (Tennessee Eastman Process) — Harvard Dataverse
echo "[1/6] TEP — requires pyreadr. Download manually from:"
echo "       https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/6C3JR1"
echo "       Place TEP_FaultFree_Training.RData and TEP_Faulty_Training.RData in $RAW_DIR/"

# 2. SKAB — Skoltech Anomaly Benchmark
echo "[2/6] SKAB — cloning from GitHub..."
if [ ! -d "$RAW_DIR/skab_repo" ]; then
    git clone https://github.com/waico/SKAB.git "$RAW_DIR/skab_repo" --depth 1
    echo "       SKAB downloaded."
else
    echo "       SKAB already exists."
fi

# 3. SMD (Server Machine Dataset)
echo "[3/6] SMD — download from OmniAnomaly repo:"
echo "       https://github.com/NetManAIOps/OmniAnomaly"
echo "       Preprocess into $RAW_DIR/smd_combined.csv"
echo "       (concatenate machine-1-1 through machine-3-11, add anomaly column)"

# 4. MSL (Mars Science Laboratory)
echo "[4/6] MSL — download from telemanom repo:"
echo "       https://github.com/khundman/telemanom"
echo "       Or Google Drive: https://drive.google.com/drive/folders/1svQtrnD0mB-4Upc_t-NX2LRvXFRQ56Bz"
echo "       Preprocess into $RAW_DIR/msl_combined.csv"

# 5. PSM (Pooled Server Metrics)
echo "[5/6] PSM — download from eBay RANSynCoders repo:"
echo "       https://github.com/eBay/RANSynCoders"
echo "       Preprocess into $RAW_DIR/psm_combined.csv"

# 6. HAI (HIL-based Augmented ICS)
echo "[6/6] HAI — download from:"
echo "       https://github.com/icsdataset/hai"
echo "       Preprocess into $RAW_DIR/hai_combined.csv (exclude 'time' column)"

echo ""
echo "=== Synthetic datasets (no download needed) ==="
echo "  SWaT: Generated by src/utils/synthetic_datasets.py"
echo "  NASA: Generated by src/utils/data_loader.py (nasa_bearing_synthetic.csv)"
echo ""
echo "After downloading, verify with:"
echo "  python -c \"from src.utils import list_datasets, get_dataset"
echo "  for name in list_datasets():"
echo "      try:"
echo "          X,y,_,_,cols,_ = get_dataset(name)"
echo "          print(f'{name:6s}: {len(cols)} channels, {X.shape[0]} samples')"
echo "      except: print(f'{name:6s}: NOT AVAILABLE')\""
